### ISSUE TITLE
Requires a peer of ****

### ISSUE THREAD

**Issue by mitchal01** [AirFusion45/Power-Bot#47]
c:\Users\techi\Documents\A\Power-Bot-master>npm install
npm WARN discord.js@11.3.2 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js-commando@0.9.0 requires a peer of sqlite@^2.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN mydiscordbot@2.8.2 No repository field.

up to date in 4.823s

c:\Users\techi\Documents\A\Power-Bot-master>npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\techi\AppData\Roaming\npm-cache\_logs\2018-07-09T00_51_43_355Z-debug.log

c:\Users\techi\Documents\A\Power-Bot-master>

**Comment by mitchal01** [comment]
I did not delete the node modules folder i only deleted the .vscode folder.

**Comment by mitchal01** [comment]
c:\Users\techi\Documents\A\Power-Bot-master>npm install

> integer@1.0.5 install c:\Users\techi\Documents\A\Power-Bot-master\node_modules\integer
> node-gyp rebuild


c:\Users\techi\Documents\A\Power-Bot-master\node_modules\integer>if not defined npm_config_node_gyp (node "C:\Users\techi\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\techi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\techi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\techi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\techi\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\techi\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\techi\Documents\A\Power-Bot-master\node_modules\integer
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN discord.js@11.3.2 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js-commando@0.9.0 requires a peer of sqlite@^2.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN mydiscordbot@2.8.2 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@1.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@1.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\techi\AppData\Roaming\npm-cache\_logs\2018-07-09T01_07_37_076Z-debug.log

c:\Users\techi\Documents\A\Power-Bot-master>npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\techi\AppData\Roaming\npm-cache\_logs\2018-07-09T01_07_59_547Z-debug.log

c:\Users\techi\Documents\A\Power-Bot-master>

**Comment by mitchal01** [comment]
c:\Users\techi\Documents\A\Power-Bot-master>npm install

> integer@1.0.5 install c:\Users\techi\Documents\A\Power-Bot-master\node_modules\integer
> node-gyp rebuild


c:\Users\techi\Documents\A\Power-Bot-master\node_modules\integer>if not defined npm_config_node_gyp (node "C:\Users\techi\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\techi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\techi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\techi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\techi\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\techi\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\techi\Documents\A\Power-Bot-master\node_modules\integer
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN mydiscordbot@2.8.2 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@1.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@1.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\techi\AppData\Roaming\npm-cache\_logs\2018-07-09T01_44_07_212Z-debug.log

c:\Users\techi\Documents\A\Power-Bot-master>node .
module.js:674
    throw err;
    ^

SyntaxError: c:\Users\techi\Documents\A\Power-Bot-master\config.json: Unexpected string in JSON at position 543
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:671:27)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\Users\techi\Documents\A\Power-Bot-master\index.js:6:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)

c:\Users\techi\Documents\A\Power-Bot-master>

**Comment by mitchal01** [comment]
I went to the recources tab and got this message
 c:\Users\techi\Documents\A\Power-Bot-2.8.0>npm install

> spawn-sync@1.0.15 postinstall c:\Users\techi\Documents\A\Power-Bot-2.8.0\node_modules\spawn-sync
> node postinstall

npm WARN mydiscordbot@2.8.0 No repository field.

added 338 packages from 232 contributors and audited 524 packages in 44.314s
found 38 vulnerabilities (6 low, 23 moderate, 9 high)
  run `npm audit fix` to fix them, or `npm audit` for details

c:\Users\techi\Documents\A\Power-Bot-2.8.0>node .
module.js:674
    throw err;
    ^

SyntaxError: c:\Users\techi\Documents\A\Power-Bot-2.8.0\config.json: Unexpected string in JSON at position 553
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:671:27)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\Users\techi\Documents\A\Power-Bot-2.8.0\index.js:6:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)

c:\Users\techi\Documents\A\Power-Bot-2.8.0>

**Comment by AirFusion45** [comment]
This is not a bug, I forgot to update the readme.md instructions. 
Follow the instructions in the readme.md until this point: `Then run the following commands:`
then:
Please use this link: https://gist.github.com/eslachance/5c539ccebde9fa76340fb5d54889aa22#installation to install. Please only install the SQLite version. After following the install instructions that is in the link, continue to the instruction in the readme. Starting from `Then run the following commands:`.
Let me know if you have any questions.

**Comment by AirFusion45** [comment]
@me (this is just a note for me, please disregard) Fix readme.md asap, causing confusion. squeeze evie's instructions above npm install. Put note about python and the stupid npm version, just incase that happens to anyone.

**Comment by AirFusion45** [comment]
old issue. Assuming resolved. Closed.
Reopen this issue or new issue if the issue persists.
