### ISSUE TITLE
welcome msgs fail to pioritize the "general" channel. This may be a good thing as people can just put #welcome/welcome channel at first

### ISSUE THREAD

**Issue by AirFusion45** [AirFusion45/Power-Bot#71]
welcome msgs fail to send their msgs first to the general channels if a server has one. Issue happened after fixing the deprecation warnings (this Ln failed: https://github.com/AirFusion45/Power-Bot/blob/892c0de0eddfc5ac7b87233a67f87e5ed06d5d7e/index.js#L164). Willing to return to prev implementation if needed.

**Comment by AirFusion45** [comment]
Consider if fixing. people can just put the welcome channel at first. which prevents all the garbage being sent to #general. where people generally chat.

**Comment by ethamitc** [comment]
Why not use the `Guild.defaultChannel`? This gets the default or "general" channel of the Discord Guild. Just do this: `Guild.defaultChannel.send('Welcome to the server!');` This would get the guilds default channel and then send the message.

**Comment by AirFusion45** [comment]
I tried this, but if the server does not have a general channel, then the welcome command would fail. So the current code I have is suppose to detect if there is a general channel. If there is, send the welcome msg to there, otherwise send it to the first channel that the bot can speak in. But thank you for helping :)

**Comment by ethamitc** [comment]
`Guild.defaultChannel` Uses the first created Guild channel, therefore there should be no way it shall fail unless it's a permissions issue!

**Comment by ethamitc** [comment]
Ok, how about this then, use Enmap to store the ID of the channel they want. So they run a command like `[PREFIX]welcome #channel` and that will get the id of the channel and store it in an Enmap collection under the guild id. So when a user joins you would just do `guild.channels.find(t => t.id == Enmap.find(guildID)).send()`.

**Comment by ethamitc** [comment]
**Update:** I have just created a pull request with these updates.

**Comment by AirFusion45** [comment]
okay :)

**Comment by AirFusion45** [comment]
Thanks for your contribution. I will test it out and if I have any more questions, I will reach out to you.
I am leaving the issue open as of now, but once I test it and make sure it is working they way I want it to, I will close the issue! Thanks!

**Comment by AirFusion45** [comment]
Made some changes. See commit desc for details!
https://github.com/AirFusion45/Power-Bot/commit/dcc1edea176f0ec818ffa376b1f272b76da9a47a

**Comment by ethamitc** [comment]
@AirFusion45 I see you edited my PR, however, you didn't edit the commands/welcome.js file to not use the Emap that you had removed. I suggest editing commands/welcome.js to rectify the issues.

**Comment by AirFusion45** [comment]
Yep, I saw that. I will fix that in the next commit. So far everything is working as intended. So issue is closed.
