### ISSUE TITLE
Enhancement - better botinfo pgage

### ISSUE THREAD

**Issue by AirFusion45** [AirFusion45/Power-Bot#72]
better/more user readable botinfo page, not just technical stuff that most users wont understand. ex: http://prntscr.com/lfpich
#enhancement.

actions:

-botinfo nerd [like google's stats for nerds] - returns highly technical botinfo pg
-botinfo - returns normal botinfo page like http://prntscr.com/lfpich

**Comment by ethamitc** [comment]
I can work on this later today :)

**Comment by AirFusion45** [comment]
Actually, this is pretty easy, the next update is still pretty far away. I will work on it myself. Thanks for the contributions.

**Comment by ethamitc** [comment]
Aight.
