### ISSUE TITLE
Move source code to src folder

### ISSUE THREAD

**Issue by ethamitc** [AirFusion45/Power-Bot#79]
As of right now, all of the source code for Power Bot is in the root of the repo `./`. I recommend moving the source code to a `./src` folder so that the main directory isn't as cluttered.

**Comment by AirFusion45** [comment]
Um, I considered that, but since I would have to reprogram all of my message handlers, I decided not to.

**Comment by AirFusion45** [comment]
I mean it makes no difference anyways in terms of functionality of the bot

**Comment by AirFusion45** [comment]
closing.
