### ISSUE TITLE
add an error msg when # of requests for -yt has been reached

### ISSUE THREAD

**Issue by AirFusion45** [AirFusion45/Power-Bot#81]

**Comment by AirFusion45** [comment]
try using a try() catch() system

**Comment by ethamitc** [comment]
I'm not sure what YT library you use, but with the function that makes the api call to YouTube their could be a `.catch()` subfunction. I would check the API docs.

**Comment by AirFusion45** [comment]
I have implemented a .catch() function to catch errors. This needs more testing. Which won't really happen that development of PowerBot has stopped. So meanwhile I will close this issue. Thanks for supporting PowerBot! :)
